server:
  port: 7000

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saga_sale
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  kafka:
    producer:
      bootstrap-servers: localhost:9092

topic:
  name:
    producer: sale